### ISSUE TITLE
clientraw.txt missing extratemp value

### ISSUE THREAD

**Issue by venirb** [gjr80/weewx-saratoga#18]
I installed an additional temperature sensor, but the value does not show in clientraw.txt. There (in clientraw.txt) at position 20 there is a value of "-100" instead of the current value. How can I fix this?

**Comment by gjr80** [comment]
Extra temperature and humidity fields are supported but require an `[[[ExtraSensors]]]` stanza being added under `[WeewxSaratoga]` `[[RealtimeClientraw]]` in `weewx.conf`. Not only is this not documented, but rtcr should work with the standard WeeWX `extraTempx` and `extraHumidx` fields out of the box rather than forcing the user to specify them. 

I've changed this behaviour in rtcr v0.3.5 and provided your extra temperature data is in WeeWX field `extraTemp1`, v0.3.5 will automatically populate field #20 with your additional temperature sensor data. If your data is in a field other than `extraTemp1`, then you will need to add something like the following under `[WeewxSaratoga]` `[[RealtimeClientraw]]` in `weewx.conf`:
```
[[[ExtraSensors]]]
    extraTempSensor1 = my_temperature_field
```
where `my_temperature_field` is the name of the WeeWX field containing your additional temperature sensor data.

You can download `rtcr.py` v0.3.5 using the following:
```
$ wget -P /var/tmp https://raw.githubusercontent.com/gjr80/weewx-saratoga/main/bin/user/rtcr.py
```

Then just copy the downloaded v0.3.5 from `/var/tmp` over the top of your existing `rtcr.py` in `/home/weewx/bin/user` (or `usr/share/weewx/user` if you did a WeeWX package install)  . You will need to restart WeeWX after changing `rtcr.py` and/or `weewx.conf`.

**Comment by venirb** [comment]
I did this as described. The problem is solved. Clientraw.text field #20 now is populated with extratemp1 value. Thanks.

**Comment by gjr80** [comment]
Thanks for letting me know. I will close this and include the updated `rtcr.py` in the next release.
