### ISSUE TITLE
Saratoga template fatal errors within 1 hr of weewx startup

### ISSUE THREAD

**Issue by ktrue** [gjr80/weewx-saratoga#23]
Updated to Weewx 4.10.2 and weewx-saratoga 0.1.7 and started weewx.
For the first hour after startup, the following tags in WEEWXtags.php had non-numeric values:
```
$tempchangehour = '--';   // Temperature change in the last hour

$humchangelasthour = '--';  // Humidity change last hour
$dewchangelasthour = '--'; // Dew point change last hour
$barochangelasthour = '--';   // Baro change last hour

$trend = '--';  // amount of change in the last hour
$trend3hour = '--';  // amount of change in the last 3 hours
```
I realize those are the 'missing' value string.  Unfortunately, in ajax-dashboard.php, ajax-gizmo.php they cause fatal errors (Non numeric) with PHP 8.2.1.
Given that the multi-hour (3hr, 24hr) values were obtained from the db and displayed correctly, couldn't the values from 1hr ago in the db be returned instead?

The net effect of the current method means a broken site for 1 hour after weewx startup can happen.

**Comment by gjr80** [comment]
'ago' fields are populated from the database using the WeeWX `$trend` tag which hits the database for the 'current' value and the value `$time_delta` seconds ago and returns the difference between the two, relevant lines from the `WEEWXtags.php` template below:
```
#raw $tempchangehour = #end raw '$trend($time_delta=3600).outTemp.format(add_label=False, localize=$localize_num)';   // Temperature change in the last hour
#raw $humchangelasthour = #end raw '$trend($time_delta=3600).outHumidity.format(format_string=$hum_sign_format, add_label=False, localize=$localize_num)';  // Humidity change last hour
#raw $dewchangelasthour = #end raw '$trend($time_delta=3600).dewpoint.format(format_string=$temp_sign_format, add_label=False, localize=$localize_num)'; // Dew point change last hour
#raw $barochangelasthour = #end raw '$trend($time_delta=3600).barometer.format(format_string=$baro_sign_format, add_label=False, localize=$localize_num)';   // Baro change last hour

#raw $trend = #end raw '$trend($time_delta=3600).barometer.format(add_label=False, localize=$localize_num)';  // amount of change in the last hour
#raw $trend3hour = #end raw '$trend($time_delta=10800).barometer.format(add_label=False, localize=$localize_num)';  // amount of change in the last 3 hours
```

If we are seeing '--' that indicates the respective `$trend` tag is returning the python value None (which the template is set, by default, to display '--'. None/'--' could be being returned due to one of the following conditions:
- the current value of the observation concerned is None or otherwise non-existent
- the value of the observation concerned `$time_delta` seconds ago is None or the record does not exist
Note that when searching for a record `$trend` considers a record to exist if the record is timestamped within 300 seconds either side of the actual timestamp specified, so `$trend($time_delta=3600)` will look for a record from 3900 seconds ago to 3300 seconds ago. If more than one records are found the one closest to the specified timestamp (in this case 3600 seconds ago) is used.

First thing I would be doing is to look at the database and see if there is data in the archive table 3600 and 10800 seconds ago. 

In terms of displaying '--' when there is no data, is there something better we can use? Happy to change if there is something better we can use. Many years ago I puzzled over this, obvious choices were an empty string '', 0, 'N/A' (the WeeWX default) and I eventually settled on '--' - every other choice had issues when displayed on a page/processed by PHP.

**Comment by ktrue** [comment]
I have a thought that this issue was caused by genuinely missing data due to my 1hr timesync issue.  using '--' for no data is appropriate, so I'd leave the code as it is.
I'll close this issue as I think we've found the underlying issue.  Thanks!
